# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "主页"
  url = "/"
  weight = 10

[[main]]
  name = "博客"
  url = "#posts"
  weight = 20

[[main]]
  name = "项目"
  url = "#projects"
  weight = 30

[[main]]
  name = "论文著作"
  url = "#publications"
  weight = 40

[[main]]
  name = "教程"
  url = "courses/example/"
  weight = 50

[[main]]
  name = "联系"
  url = "#contact"
  weight = 60

[[main]]
  name = "合作与赞助"
  url = "/donate/"
  weight = 70


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
